export const BOOKS = [
  { id: 'GEN', osis: 'Gen', name: 'Génesis', abbrevs: ['gn', 'gen', 'gén', 'genesis', 'génesis'] },
  { id: 'EXO', osis: 'Exod', name: 'Éxodo', abbrevs: ['ex', 'exo', 'éx', 'exodo', 'éxodo'] },
  { id: 'LEV', osis: 'Lev', name: 'Levítico', abbrevs: ['lv', 'lev', 'levitico', 'levítico'] },
  { id: 'NUM', osis: 'Num', name: 'Números', abbrevs: ['nm', 'num', 'núm', 'numeros', 'números'] },
  { id: 'DEU', osis: 'Deut', name: 'Deuteronomio', abbrevs: ['dt', 'deu', 'deut', 'deuteronomio'] },
  { id: 'JOS', osis: 'Josh', name: 'Josué', abbrevs: ['jos', 'josue', 'josué'] },
  { id: 'JDG', osis: 'Judg', name: 'Jueces', abbrevs: ['jc', 'jue', 'juec', 'jueces'] },
  { id: 'RUT', osis: 'Ruth', name: 'Rut', abbrevs: ['rt', 'rut', 'ruth'] },
  { id: '1SA', osis: '1Sam', name: '1 Samuel', abbrevs: ['1s', '1sa', '1sam', '1samuel'] },
  { id: '2SA', osis: '2Sam', name: '2 Samuel', abbrevs: ['2s', '2sa', '2sam', '2samuel'] },
  { id: '1KI', osis: '1Kgs', name: '1 Reyes', abbrevs: ['1r', '1re', '1rey', '1reyes'] },
  { id: '2KI', osis: '2Kgs', name: '2 Reyes', abbrevs: ['2r', '2re', '2rey', '2reyes'] },
  { id: '1CH', osis: '1Chr', name: '1 Crónicas', abbrevs: ['1cr', '1cro', '1cron', '1cronicas', '1crónicas'] },
  { id: '2CH', osis: '2Chr', name: '2 Crónicas', abbrevs: ['2cr', '2cro', '2cron', '2cronicas', '2crónicas'] },
  { id: 'EZR', osis: 'Ezra', name: 'Esdras', abbrevs: ['esd', 'esdras'] },
  { id: 'NEH', osis: 'Neh', name: 'Nehemías', abbrevs: ['neh', 'nehemias', 'nehemías'] },
  { id: 'EST', osis: 'Esth', name: 'Ester', abbrevs: ['est', 'ester'] },
  { id: 'JOB', osis: 'Job', name: 'Job', abbrevs: ['jb', 'job'] },
  { id: 'PSA', osis: 'Ps', name: 'Salmos', abbrevs: ['sl', 'sal', 'salm', 'salmo', 'salmos'] },
  { id: 'PRO', osis: 'Prov', name: 'Proverbios', abbrevs: ['pr', 'pro', 'prov', 'proverbios'] },
  { id: 'ECC', osis: 'Eccl', name: 'Eclesiastés', abbrevs: ['ec', 'ecl', 'ecle', 'eclesiastes', 'eclesiastés'] },
  { id: 'SNG', osis: 'Song', name: 'Cantares', abbrevs: ['cnt', 'cant', 'cantar', 'cantares'] },
  { id: 'ISA', osis: 'Isa', name: 'Isaías', abbrevs: ['is', 'isa', 'isaias', 'isaías'] },
  { id: 'JER', osis: 'Jer', name: 'Jeremías', abbrevs: ['jr', 'jer', 'jeremias', 'jeremías'] },
  { id: 'LAM', osis: 'Lam', name: 'Lamentaciones', abbrevs: ['lm', 'lam', 'lamentaciones'] },
  { id: 'EZK', osis: 'Ezek', name: 'Ezequiel', abbrevs: ['ez', 'eze', 'ezeq', 'ezequiel'] },
  { id: 'DAN', osis: 'Dan', name: 'Daniel', abbrevs: ['dn', 'dan', 'daniel'] },
  { id: 'HOS', osis: 'Hos', name: 'Oseas', abbrevs: ['os', 'ose', 'oseas'] },
  { id: 'JOL', osis: 'Joel', name: 'Joel', abbrevs: ['jl', 'joe', 'joel'] },
  { id: 'AMO', osis: 'Amos', name: 'Amós', abbrevs: ['am', 'amo', 'amos', 'amós'] },
  { id: 'OBA', osis: 'Obad', name: 'Abdías', abbrevs: ['abd', 'abdias', 'abdías'] },
  { id: 'JON', osis: 'Jonah', name: 'Jonás', abbrevs: ['jon', 'jonas', 'jonás'] },
  { id: 'MIC', osis: 'Mic', name: 'Miqueas', abbrevs: ['mi', 'miq', 'miqueas'] },
  { id: 'NAM', osis: 'Nah', name: 'Nahúm', abbrevs: ['nah', 'nahum', 'nahúm'] },
  { id: 'HAB', osis: 'Hab', name: 'Habacuc', abbrevs: ['hab', 'habacuc'] },
  { id: 'ZEP', osis: 'Zeph', name: 'Sofonías', abbrevs: ['sof', 'sofonias', 'sofonías'] },
  { id: 'HAG', osis: 'Hag', name: 'Hageo', abbrevs: ['hag', 'ageo', 'hageo'] },
  { id: 'ZEC', osis: 'Zech', name: 'Zacarías', abbrevs: ['zc', 'zac', 'zacarias', 'zacarías'] },
  { id: 'MAL', osis: 'Mal', name: 'Malaquías', abbrevs: ['mal', 'malaquias', 'malaquías'] },
  { id: 'MAT', osis: 'Matt', name: 'Mateo', abbrevs: ['mt', 'mat', 'mateo', 'smateo', 'sanmateo'] },
  { id: 'MRK', osis: 'Mark', name: 'Marcos', abbrevs: ['mr', 'mc', 'mar', 'marcos', 'smarcos', 'sanmarcos'] },
  { id: 'LUK', osis: 'Luke', name: 'Lucas', abbrevs: ['lc', 'luc', 'lucas', 'slucas', 'sanlucas'] },
  { id: 'JHN', osis: 'John', name: 'Juan', abbrevs: ['jn', 'jua', 'juan', 'sjuan', 'sanjuan'] },
  { id: 'ACT', osis: 'Acts', name: 'Hechos', abbrevs: ['hch', 'hec', 'hechos'] },
  { id: 'ROM', osis: 'Rom', name: 'Romanos', abbrevs: ['ro', 'rm', 'rom', 'romanos'] },
  { id: '1CO', osis: '1Cor', name: '1 Corintios', abbrevs: ['1co', '1cor', '1corintios'] },
  { id: '2CO', osis: '2Cor', name: '2 Corintios', abbrevs: ['2co', '2cor', '2corintios'] },
  { id: 'GAL', osis: 'Gal', name: 'Gálatas', abbrevs: ['ga', 'gal', 'galatas', 'gálatas'] },
  { id: 'EPH', osis: 'Eph', name: 'Efesios', abbrevs: ['ef', 'efe', 'efesios'] },
  { id: 'PHP', osis: 'Phil', name: 'Filipenses', abbrevs: ['fil', 'flp', 'filip', 'filipenses'] },
  { id: 'COL', osis: 'Col', name: 'Colosenses', abbrevs: ['col', 'colosenses'] },
  { id: '1TH', osis: '1Thess', name: '1 Tesalonicenses', abbrevs: ['1ts', '1te', '1tes', '1tesalonicenses'] },
  { id: '2TH', osis: '2Thess', name: '2 Tesalonicenses', abbrevs: ['2ts', '2te', '2tes', '2tesalonicenses'] },
  { id: '1TI', osis: '1Tim', name: '1 Timoteo', abbrevs: ['1ti', '1tim', '1timoteo'] },
  { id: '2TI', osis: '2Tim', name: '2 Timoteo', abbrevs: ['2ti', '2tim', '2timoteo'] },
  { id: 'TIT', osis: 'Titus', name: 'Tito', abbrevs: ['tit', 'tito'] },
  { id: 'PHM', osis: 'Phlm', name: 'Filemón', abbrevs: ['flm', 'film', 'filemon', 'filemón'] },
  { id: 'HEB', osis: 'Heb', name: 'Hebreos', abbrevs: ['he', 'heb', 'hebreos'] },
  { id: 'JAS', osis: 'Jas', name: 'Santiago', abbrevs: ['stg', 'sant', 'santiago'] },
  { id: '1PE', osis: '1Pet', name: '1 Pedro', abbrevs: ['1p', '1pe', '1ped', '1pedro'] },
  { id: '2PE', osis: '2Pet', name: '2 Pedro', abbrevs: ['2p', '2pe', '2ped', '2pedro'] },
  { id: '1JN', osis: '1John', name: '1 Juan', abbrevs: ['1jn', '1jua', '1juan'] },
  { id: '2JN', osis: '2John', name: '2 Juan', abbrevs: ['2jn', '2jua', '2juan'] },
  { id: '3JN', osis: '3John', name: '3 Juan', abbrevs: ['3jn', '3jua', '3juan'] },
  { id: 'JUD', osis: 'Jude', name: 'Judas', abbrevs: ['jud', 'judas'] },
  { id: 'REV', osis: 'Rev', name: 'Apocalipsis', abbrevs: ['ap', 'apo', 'apoc', 'apocalipsis'] }
]
